// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_repository.go -source=./repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/grabomska/shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(shortUrl *model.ShortUrl) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", shortUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(shortUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), shortUrl)
}

// GetByShort mocks base method.
func (m *MockRepository) GetByShort(short string) (*model.ShortUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShort", short)
	ret0, _ := ret[0].(*model.ShortUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShort indicates an expected call of GetByShort.
func (mr *MockRepositoryMockRecorder) GetByShort(short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShort", reflect.TypeOf((*MockRepository)(nil).GetByShort), short)
}

// GetByUrl mocks base method.
func (m *MockRepository) GetByUrl(url string) (*model.ShortUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUrl", url)
	ret0, _ := ret[0].(*model.ShortUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUrl indicates an expected call of GetByUrl.
func (mr *MockRepositoryMockRecorder) GetByUrl(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUrl", reflect.TypeOf((*MockRepository)(nil).GetByUrl), url)
}
