// Code generated by MockGen. DO NOT EDIT.
// Source: ./shortener.go
//
// Generated by this command:
//
//	mockgen -destination ./mocks/mock_shortener.go -source ./shortener.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/grabomska/shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockShortenerServiceInterface is a mock of ShortenerServiceInterface interface.
type MockShortenerServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockShortenerServiceInterfaceMockRecorder is the mock recorder for MockShortenerServiceInterface.
type MockShortenerServiceInterfaceMockRecorder struct {
	mock *MockShortenerServiceInterface
}

// NewMockShortenerServiceInterface creates a new mock instance.
func NewMockShortenerServiceInterface(ctrl *gomock.Controller) *MockShortenerServiceInterface {
	mock := &MockShortenerServiceInterface{ctrl: ctrl}
	mock.recorder = &MockShortenerServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerServiceInterface) EXPECT() *MockShortenerServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockShortenerServiceInterface) CreateShortURL(url string) (*model.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", url)
	ret0, _ := ret[0].(*model.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockShortenerServiceInterfaceMockRecorder) CreateShortURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockShortenerServiceInterface)(nil).CreateShortURL), url)
}

// GetFullURLByShort mocks base method.
func (m *MockShortenerServiceInterface) GetFullURLByShort(short string) (*model.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullURLByShort", short)
	ret0, _ := ret[0].(*model.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullURLByShort indicates an expected call of GetFullURLByShort.
func (mr *MockShortenerServiceInterfaceMockRecorder) GetFullURLByShort(short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullURLByShort", reflect.TypeOf((*MockShortenerServiceInterface)(nil).GetFullURLByShort), short)
}
