// Code generated by MockGen. DO NOT EDIT.
// Source: ./shortener.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_shortener.go -source=./shortener.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/grabomska/shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockShortenerServiceInterface is a mock of ShortenerServiceInterface interface.
type MockShortenerServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockShortenerServiceInterfaceMockRecorder is the mock recorder for MockShortenerServiceInterface.
type MockShortenerServiceInterfaceMockRecorder struct {
	mock *MockShortenerServiceInterface
}

// NewMockShortenerServiceInterface creates a new mock instance.
func NewMockShortenerServiceInterface(ctrl *gomock.Controller) *MockShortenerServiceInterface {
	mock := &MockShortenerServiceInterface{ctrl: ctrl}
	mock.recorder = &MockShortenerServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerServiceInterface) EXPECT() *MockShortenerServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateShortUrl mocks base method.
func (m *MockShortenerServiceInterface) CreateShortUrl(url string) (*model.ShortUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortUrl", url)
	ret0, _ := ret[0].(*model.ShortUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortUrl indicates an expected call of CreateShortUrl.
func (mr *MockShortenerServiceInterfaceMockRecorder) CreateShortUrl(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortUrl", reflect.TypeOf((*MockShortenerServiceInterface)(nil).CreateShortUrl), url)
}

// GetFullUrlByShort mocks base method.
func (m *MockShortenerServiceInterface) GetFullUrlByShort(short string) (*model.ShortUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullUrlByShort", short)
	ret0, _ := ret[0].(*model.ShortUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullUrlByShort indicates an expected call of GetFullUrlByShort.
func (mr *MockShortenerServiceInterfaceMockRecorder) GetFullUrlByShort(short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullUrlByShort", reflect.TypeOf((*MockShortenerServiceInterface)(nil).GetFullUrlByShort), short)
}
